aiurdemux: Use GST_TAG_LOCATION tag for USER_DATA_LOCATION
-1 is not a string and GST_TAG_LOCATION is defined in gst/gsttaglist.h
as "location", this fixes build error with clang

plugins/aiurdemux/aiurdemux.c:198:47: error: incompatible integer to pointer conversion initializing 'const gchar
*' (aka 'const char *') with an expression of type 'int' [-Wint-conversion]
|   {USER_DATA_LOCATION, USER_DATA_FORMAT_UTF8, -1,
|                                               ^~

Signed-off-by: Khem Raj <raj.khem@gmail.com>