Change spdifparser header files path
Commit reason: The headers are not in the mentioned location in the Makefile.am file, that causes a build break:

ERROR: No rule to make target 'ext-includes/spdif_parser/spdifparser_types.h', needed by 'all-am'. Stop.

So update the Makefile.am to reflect the actual header's path

Signed-off-by: Valentin Jec <valentin.jec@nxp.com>