gstimxcommon: Return 0 instead of NULL for a functions returning unsigned long
Fixes
gstimxcommon.c:113:10: error: incompatible pointer to integer conversion returning 'void *' from a function with result type 'unsigned long' [-Wint-conversion]
  return NULL;

Signed-off-by: Khem Raj <raj.khem@gmail.com>